INSERT INTO maps (user_id, title, description)
     VALUES (1, 'Construction Sites', 'Current constructions going on around Vancouver. Be careful of manholes!')
          , (3, 'Food is Life', 'The title says it all. Food 4eva!!!')
          , (4, 'Bird Watching Spots', 'Grab a chair and sit at these spots to look at birds.')
          , (1, 'Nightlife Crawl', 'Explore all of the best spots and party until the sun comes up.')
          , (4, 'Hair Salons', 'Hit up these salons to rock that new hair style.')
          , (3, 'Pet Food Store', 'Find the best spots to feed your hungry pooch.')
          , (4, 'Gyms', 'Shed that winter weight before you hit the beach.')
          , (1, 'Parks', 'Explore the best parks the city has to offer.')
          , (2, 'Brewerys', 'Hit up the best craft brewery spots in town.')
          ;
