DROP TABLE IF EXISTS maps CASCADE;
CREATE TABLE maps (
  id SERIAL PRIMARY KEY NOT NULL
  , user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
  , title VARCHAR(255) NOT NULL
  , description TEXT
  , created_on TIMESTAMP NOT NULL
);
