DROP TABLE IF EXISTS points CASCADE;
CREATE TABLE points (
  id SERIAL PRIMARY KEY NOT NULL
  , map_id INTEGER NOT NULL REFERENCES maps(id) ON DELETE CASCADE
  , user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
  , title VARCHAR(255) NOT NULL
  , description TEXT
  , longitude FLOAT
  , latitude FLOAT
  , image_url VARCHAR(255) NOT NULL
);


